import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Tulika',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Jayesh',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Slim dress',
      category: 'Dress',
      image: '/images/p1.jpg',
      image1: '/images/p1h1.jpg',
      image2: '/images/p1h2.jpg',
      price: 55,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4,
      numReviews: 10,
      description: 'high quality dress',
    },
    {
      name: 'Black-Dress',
      category: 'Dress',
      image: '/images/p2.jpg',
      image1: '/images/p2h1.jpg',
      image2: '/images/p2h2.jpg',
      price: 60,
      countInStock: 0,
      brand: 'Nike',
      rating: 3,
      numReviews: 10,
      description: 'high quality dress',
    },
    {
      name: 'Puma Jeans',
      category: 'Jeans',
      image: '/images/p3.jpg',
      image1: '/images/p3h1.jpg',
      image2: '/images/p3h2.jpg',
      price: 47,
      countInStock: 3,
      brand: 'Puma',
      rating: 4,
      numReviews: 10,
      description: 'best quality jeans',
    },
    {
      name: 'Puma top',
      category: 'Top',
      image: '/images/p4.jpg',
      image1: '/images/p4h1.jpg',
      image2: '/images/p4h2.jpg',
      price: 15,
      countInStock: 18,
      brand: 'Puma',
      rating: 3,
      numReviews: 10,
      description: 'branded top',
    },
    {
      name: 'Nike top',
      category: 'Top',
      image: '/images/p5.jpg',
      image1: '/images/p5h1.jpg',
      image2: '/images/p5h2.jpg',
      price: 90,
      countInStock: 1,
      brand: 'Nike',
      rating: 3,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Pants',
      category: 'Pants',
      image: '/images/p6.jpg',
      image1: '/images/p6h1.jpg',
      image2: '/images/p6h2.jpg',
      price: 20,
      countInStock: 25,
      brand: 'Adidas',
      rating: 5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Party Dress',
      category: 'Dress',
      image: '/images/p7.jpg',
      image1: '/images/p7h1.jpg',
      image2: '/images/p7h2.jpg',
      price: 12,
      countInStock: 8,
      brand: 'Puma',
      rating: 2,
      numReviews: 10,
      description: 'high quality shirt',
    },
  ],
};
export default data;
