const data = {
  products: [
    {
      _id: '1',
      name: 'Slim dress',
      slug: 'slim-shirt',
      category: 'Dress',
      image: '/images/p1.jpg',
      image1: '/images/p1h1.jpg',
      image2: '/images/p1h2.jpg',
      price: 550,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality dress',
    },
    {
      _id: '2',
      name: 'Black-Dress',
      slug: 'nike-slim-shirt0',
      category: 'Dress',
      image: '/images/p2.jpg',
      image1: '/images/p2h1.jpg',
      image2: '/images/p2h2.jpg',
      price: 600,
      countInStock: 0,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality dress',
    },
    {
      _id: '3',
      name: 'Puma Jeans',
      slug: 'nike-slim-shirt1',
      category: 'Jeans',
      image: '/images/p3.jpg',
      image1: '/images/p3h1.jpg',
      image2: '/images/p3h2.jpg',
      price: 1000,
      countInStock: 3,
      brand: 'Puma',
      rating: 4,
      numReviews: 10,
      description: 'best quality jeans',
    },
    {
      _id: '4',
      name: 'Puma top',
      slug: 'nike-slim-shirt2',
      category: 'Top',
      image: '/images/p4.jpg',
      image1: '/images/p4h1.jpg',
      image2: '/images/p4h2.jpg',
      price: 1500,
      countInStock: 18,
      brand: 'Puma',
      rating: 3,
      numReviews: 10,
      description: 'branded top',
    },
    {
      _id: '5',
      name: 'Nike top',
      slug: 'nike-slim-shirt3',
      category: 'Top',
      image: '/images/p5.jpg',
      image1: '/images/p5h1.jpg',
      image2: '/images/p5h2.jpg',
      price: 900,
      countInStock: 1,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '6',
      name: 'Adidas Pants',
      slug: 'nike-slim-shirt4',
      category: 'Pants',
      image: '/images/p6.jpg',
      image1: '/images/p6h1.jpg',
      image2: '/images/p6h2.jpg',
      price: 2000,
      countInStock: 25,
      brand: 'Adidas',
      rating: 5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '7',
      name: 'Party Dress',
      slug: 'nike-slim-shirt5',
      category: 'Dress',
      image: '/images/p7.jpg',
      image1: '/images/p7h1.jpg',
      image2: '/images/p7h2.jpg',
      price: 1200,
      countInStock: 8,
      brand: 'Puma',
      rating: 4,
      numReviews: 10,
      description: 'high quality shirt',
    },
  ],
};
export default data;
